apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tutorial-pipeline
spec:
  params:
    - name: revision
      type: string
  resources:
    - name: source-repo
      type: git
    - name: web-image
      type: image
  tasks:
    - name: build-socks
      taskRef:
        name: build-docker-image-from-git-source
      params:
        - name: revision
          value: $(params.revision)
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/docker-source
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: web-image
    - name: deploy-web
      taskRef:
        name: deployusingkubectl
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: web-image
            from:
              - build-socks
      params:
        - name: revision
          value: $(params.revision)
        - name: path
          value: /workspace/source/deployment/front-end2.yaml
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
