variables:
  DOCKER_HOST: tcp://docker:2375


stages:
  - test
  - build
  - release
  - deploy

cache:
  paths:
  - node_modules/
  - .yarn
  
.docker_registry_template: &docker_registry
  image: docker:git
  services:
    - docker:dind
  before_script:
    - export REVISION=$(git rev-parse --short HEAD)
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} ${CI_REGISTRY}
  after_script:
    - docker logout ${CI_REGISTRY}


release:
  stage: release
  <<: *docker_registry
  script:
#    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}:latest
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}:1.1.$CI_BUILD_ID
    - docker push ${CONTAINER_IMAGE}:1.1.$CI_BUILD_ID
    - docker push ${CONTAINER_IMAGE}:latest

deploy_staging:
  stage: deploy
  image: lwolf/helm-kubectl-docker:v152_213
  before_script:
    - mkdir -p /etc/deploy
    - echo ${KUBECONFIG} | base64 -d > ${KUBECONFIG}
    - kubectl config set-context $(kubectl config current-context) --namespace=socks-shop
  script:
    - kubectl set image deployment.apps/front-end front-end=${CONTAINER_IMAGE} --record
  only:
  - master
