variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  KUBECONFIG: /etc/deploy/config
  
stages:
  - test
  - build
  - release
  - deploy
  - deploy_anthos
  - deploy_AKS

cache:
  paths:
  - node_modules/
  - .yarn



deploy_AKS:
  stage: deploy_AKS
  image: dtzar/helm-kubectl
  before_script:
    - mkdir -p /etc/deploy
    - echo ${AKS} | base64 -d > ${KUBECONFIG}
    - kubectl config set-context $(kubectl config current-context) --namespace=socks-shop

  script:
#    - sleep 1000
    - export deploymentexist="$(kubectl get pods |grep front)" 
    - if [ -z $deploymentexist ]; then kubectl apply -f /builds/demouser/front-end/deployment/front-end2.yaml;fi
    - kubectl set image deployment.apps/front-end front-end=${CONTAINER_IMAGE}:1.1.$CI_PIPELINE_IID --record
  only:
  - master
