variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  
stages:
  - test
  - build
  - release
  - deploy

cache:
  paths:
  - node_modules/
  - .yarn

deploy:
  stage: deploy
  image: lwolf/helm-kubectl-docker:v152_213
  before_script:
    - mkdir -p /etc/deploy
#    - sleep 1000
    - echo ${KUBECONFIG} > config
    - sleep 1000
    - kubectl config set-context $(kubectl config current-context) --namespace=socks-shop
  script:
    - kubectl set image deployment.apps/front-end front-end=${CONTAINER_IMAGE} --record
  only:
  - master
