variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  KUBECONFIG: /etc/deploy/config
  
stages:
  - test
  - build
  - release
  - deploy
  - deploy_anthos

cache:
  paths:
  - node_modules/
  - .yarn

deploy_anthos:
  stage: deploy_anthos
  image: dtzar/helm-kubectl
  before_script:
    - mkdir -p /etc/deploy
    - echo ${anthos} | base64 -d > ${KUBECONFIG}
    - kubectl config set-context $(kubectl config current-context) --namespace=socks-shop
  script:
#    - sleep 1000
    - deployment=`kubectl get pods |grep front`
    - if [ -z "$deployment" ]; then kubectly apply -f deployment/front-end2.yaml; else kubectl set image deployment.apps/front-end front-end=${CONTAINER_IMAGE}:1.1.$CI_PIPELINE_IID --record;fi
  only:
  - master
