variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  KUBECONFIG: /etc/deploy/config
  
stages:
  - test
  - build
  - release
  - deploy
  - deploy_anthos
  - deploy_rancher
  - deploy_AKS

cache:
  paths:
  - node_modules/
  - .yarn
  
  
Test:
  stage: test
  image: node:9.4.0
  tags:
  - node
  before_script: 
    - apt-get update -qq && apt-get install -qy libelf1
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile
  script:
     - hostname
     - NODE_ENV=dev npm install
     - PORT=8079 npm test

release:
  stage: release
  services: 
    - docker:19.03.0-dind
  image: docker:19.03.0
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}:latest
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}:1.1.$CI_PIPELINE_IID
    - docker push ${CONTAINER_IMAGE}:1.1.$CI_PIPELINE_IID
    - docker push ${CONTAINER_IMAGE}:latest

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  before_script:
    - mkdir -p /etc/deploy
    - echo ${kube_config_ga} | base64 -d > ${KUBECONFIG}
    - kubectl config set-context $(kubectl config current-context) --namespace=socks-shop
  script:
    - export deploymentexist="$(kubectl get pods |grep front)" 
    - if [ -z $deploymentexist ]; then kubectl apply -f /builds/demouser/front-end/deployment/front-end2.yaml;kubectl apply -f /builds/demouser/front-end/deployment/complete-demo.yaml;fi
    - kubectl set image deployment.apps/front-end front-end=${CONTAINER_IMAGE}:1.1.$CI_PIPELINE_IID --record
  only:
  - master
  

deploy_anthos:
  stage: deploy_anthos
  image: dtzar/helm-kubectl
  before_script:
    - mkdir -p /etc/deploy
    - echo ${anthos} | base64 -d > ${KUBECONFIG}
    - kubectl config set-context $(kubectl config current-context) --namespace=socks-shop

  script:
    - export deploymentexist="$(kubectl get pods |grep front)" 
    - if [ -z $deploymentexist ]; then kubectl apply -f /builds/demouser/front-end/deployment/front-end2.yaml;kubectl apply -f /builds/demouser/front-end/deployment/complete-demo.yaml;fi
    - kubectl set image deployment.apps/front-end front-end=${CONTAINER_IMAGE}:1.1.$CI_PIPELINE_IID --record
  only:
  - stage

deploy_rancher:
  stage: deploy_rancher
  image: dtzar/helm-kubectl
  before_script:
    - mkdir -p /etc/deploy
    - echo ${rancher} | base64 -d > ${KUBECONFIG}
    - kubectl config set-context $(kubectl config current-context) --namespace=socks-shop

  script:
    - export deploymentexist="$(kubectl get pods |grep front)" 
    - if [ -z $deploymentexist ]; then kubectl apply -f /builds/demouser/front-end/deployment/front-end2.yaml;kubectl apply -f /builds/demouser/front-end/deployment/complete-demo.yaml;fi
    - kubectl set image deployment.apps/front-end front-end=${CONTAINER_IMAGE}:1.1.$CI_PIPELINE_IID --record
  only:
  - stage
  
  
deploy_AKS:
  stage: deploy_AKS
  image: dtzar/helm-kubectl
  before_script:
    - mkdir -p /etc/deploy
    - echo ${AKS} | base64 -d > ${KUBECONFIG}
    - kubectl config set-context $(kubectl config current-context) --namespace=socks-shop
    - echo 10.42.117.34 aks.geneva3.cloudapp.azurestacksys3.hpecic.net >> /etc/hosts

  script:
    - export deploymentexist="$(kubectl get pods |grep front)" 
    - if [ -z $deploymentexist ]; then kubectl apply -f /builds/demouser/front-end/deployment/front-end2.yaml;kubectl apply -f /builds/demouser/front-end/deployment/complete-demo.yaml;fi
    - kubectl set image deployment.apps/front-end front-end=${CONTAINER_IMAGE}:1.1.$CI_PIPELINE_IID --record
  only:
  - preprod
