---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: socks-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: quay.io/nicolaso/front-end:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8079
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: socks-shop
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 8079
      protocol: TCP
#    nodePort: 30001
  selector:
    name: front-end
    app: front-end
    deploymentconfig: front-end
status:
  loadBalancer: {}
